[theme]
primaryColor = "#534AB7"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F8F9FA"
textColor = "#1e2a3a"
font = "sans serif"

[server]
headless = true

[browser]
gatherUsageStats = false
